# Generated by Django 3.2.4 on 2021-07-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
    ]
